[unstable]
profile-rustflags = true

[build]
target = "riscv64gc-unknown-none-elf"

[profile.dev.package.kernel]
rustflags = ["-C", "link-arg=-Tkernel/src/linker.ld"]

[profile.release.package.kernel]
rustflags = ["-C", "link-arg=-Tkernel/src/linker.ld"]
